#!/usr/bin/env bash
# WordLight TV — generate/refresh the Vega app for spike S1 (macOS or Ubuntu with the Vega SDK).
#
# Idempotent — safe to re-run after any change to overlay/ or packages/karaoke-core:
#   1. checks the Vega CLI
#   2. generates a Vega project from the official helloWorld template (first run only)
#   3. installs @amazon-devices/react-native-w3cmedia (+ expo-font for the Devanagari font)
#   4. adds the media manifest entries used by Amazon's vega-audio-sample
#   5. copies overlay/ (App, fonts) and vendors packages/karaoke-core into src/vendor
#   6. writes src/wordlight.config.ts (server URL = this Mac's LAN IP)
#   7. prints the build / run commands
#
# Usage (repo root):  bash apps/vega-tv/setup.sh
#   env: SERVER_URL=http://192.168.1.35:8787  STORY_ID=s1-timing  AUDIO_FILE=p1.mp3|p1.m4a  LEAD_MS=0
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
APP_NAME=WordLightTV
PKG_ID=com.wordlight.tv
APP_DIR="$HERE/$APP_NAME"
say() { printf '\n\033[1;36m▸ %s\033[0m\n' "$*"; }

[ -f "$HOME/vega/env" ] && source "$HOME/vega/env" || true
command -v vega >/dev/null 2>&1 || { echo "Vega CLI not found. Install: curl -fsSL https://sdk-installer.vega.labcollab.net/get_vvm.sh | bash && source ~/vega/env"; exit 1; }
say "Vega: $(vega --version 2>&1 | tr '\n' ' ')"

if [ ! -f "$APP_DIR/manifest.toml" ]; then
  say "Generating the Vega project from the helloWorld template"
  (cd "$HERE" && vega project generate --template helloWorld --name "$APP_NAME" --packageId "$PKG_ID" --outputDir "$APP_NAME") || {
    echo "Project generation failed. Available templates:"; vega project list-templates || true; exit 1; }
fi
cd "$APP_DIR"

say "Installing dependencies"
npm install
grep -q '"@amazon-devices/react-native-w3cmedia"' package.json || npm install @amazon-devices/react-native-w3cmedia
FONT_OK=1
# expo-font's documented dependency set (developer.amazon.com/docs/vega-api/0.24/expo-font.html):
# installing expo-font alone fails at bundle time on the missing expo-constants/expo-asset imports.
grep -q '"@amazon-devices/expo-constants"' package.json || npm install \
  "@amazon-devices/keplerscript-turbomodule-api@~1.0.0" "@amazon-devices/expo-asset@~2.0.0" \
  "@amazon-devices/expo-constants@~2.0.0" "@amazon-devices/expo-font@~2.0.0" "expo@~50.0.0" || FONT_OK=0

if ! grep -q "wordlight: media playback" manifest.toml; then
  say "Adding media manifest entries (as declared by Amazon's vega-audio-sample)"
  cat >> manifest.toml <<'TOML'

# --- wordlight: media playback (entries from AmazonAppDev/vega-audio-sample manifest.toml) ---
[[wants.service]]
id = "com.amazon.media.server"
[[wants.service]]
id = "com.amazon.media.playersession.service"
[[wants.service]]
id = "com.amazon.mediametrics.service"
[[wants.service]]
id = "com.amazon.audio.stream"
[[wants.service]]
id = "com.amazon.audio.control"
[[wants.service]]
id = "com.amazon.audio.system"
[[wants.service]]
id = "com.amazon.mediabuffer.service"
[[wants.service]]
id = "com.amazon.mediatransform.service"
[[wants.service]]
id = "com.amazon.gipc.uuid.*"
[[wants.service]]
id = "com.amazon.network.service"
[[offers.service]]
id = "com.amazon.gipc.uuid.*"
TOML
fi

say "Copying WordLight sources"
[ -f src/App.tsx ] && [ ! -f src/App.template.tsx ] && cp src/App.tsx src/App.template.tsx
cp "$HERE/overlay/src/App.tsx" src/App.tsx
if [ "$FONT_OK" = 1 ]; then cp "$HERE/overlay/src/fonts.ts" src/fonts.ts; else cp "$HERE/overlay/src/fonts.fallback.ts" src/fonts.ts; echo "expo-font unavailable: using the system font"; fi
mkdir -p assets/fonts && cp "$HERE"/overlay/assets/fonts/* assets/fonts/
rm -rf src/vendor/karaoke-core && mkdir -p src/vendor/karaoke-core
for f in "$ROOT"/packages/karaoke-core/src/*.ts; do
  # Metro resolves extension-less imports; our Node sources import './x.ts'
  sed -E "s#(from '\./[a-z-]+)\.ts'#\1'#g" "$f" > "src/vendor/karaoke-core/$(basename "$f")"
done

if [ -z "${SERVER_URL:-}" ]; then
  IP=$( (ipconfig getifaddr en0 || ipconfig getifaddr en1 || hostname -I 2>/dev/null | awk '{print $1}') 2>/dev/null | head -1)
  SERVER_URL="http://${IP:-127.0.0.1}:8787"
fi
cat > src/wordlight.config.ts <<CFG
// Generated by apps/vega-tv/setup.sh — re-run it to change these.
export const SERVER_URL = '${SERVER_URL}';
export const STORY_ID = '${STORY_ID:-s1-timing}';
export const AUDIO_FILE = '${AUDIO_FILE:-p1.mp3}';
// ms to light words EARLIER than the audio position (cancels measured output latency). 0 until S1 measures it.
export const LEAD_MS = ${LEAD_MS:-0};
CFG
say "Baked in: server ${SERVER_URL} · story ${STORY_ID:-s1-timing} · audio ${AUDIO_FILE:-p1.mp3} · lead ${LEAD_MS:-0} ms"

COMPONENT=$(grep -A2 '\[\[components.interactive\]\]' manifest.toml | grep '^id' | head -1 | sed -E 's/.*"(.*)".*/\1/')
say "Build scripts in package.json:"
node -e "const s=require('./package.json').scripts||{}; for (const k of Object.keys(s)) if (/build|start|bundle/.test(k)) console.log('  npm run '+k+'   # '+s[k])"
cat <<EOT

Next (each in its own terminal where noted):
  A. Server + S1 media (repo root):   npm run s1:media && npm start
  B. Build:                           cd $APP_DIR && npm run build:debug     (or: npx react-native build-vega)
  C. Virtual Device:                  vega virtual-device start
  D. Run:                             vega run-app \$(ls build/*debug*/*.vpkg | head -1) ${COMPONENT} -d VirtualDevice
  E. Logs:                            vega device start-log-stream --device VirtualDevice | grep wordlight
EOT
