// Dev e2e: fake TV (WebSocket) + real phone page (Chromium, fake mic) + server with SPEECH=sim.
import { chromium } from 'playwright-core';
import WebSocket from 'ws';
const BASE = process.env.WL_SERVER || 'http://localhost:8800';
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const log = (...a) => console.log(...a);
const { sessionId: sid, joinUrl } = await (await fetch(`${BASE}/api/sessions`, { method: 'POST' })).json();
log('session', sid, 'join', joinUrl);
const tvMsgs = [];
const tv = new WebSocket(BASE.replace('http', 'ws') + '/ws');
await new Promise((r) => tv.on('open', r));
tv.send(JSON.stringify({ t: 'hello', role: 'tv', sessionId: sid, clientId: 'tv' }));
tv.on('message', (d) => tvMsgs.push(JSON.parse(d.toString())));
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM, args: ['--use-fake-ui-for-media-stream', '--use-fake-device-for-media-stream'] });
const page = await (await browser.newContext()).newPage();
page.on('pageerror', (e) => log('  [pageerror]', e.message));
await page.goto(`${BASE}/j/${sid}`); await sleep(1200);
const vis = (id) => page.$eval('#' + id, (e) => !e.classList.contains('hidden') && getComputedStyle(e).display !== 'none');
log('A load: consent', await vis('consent-card'), 'reader', await vis('reader-card'), 'diag rows hidden', !(await vis('conn-card')));
await page.click('#consent-btn'); await sleep(300);
log('B after consent: reader card', await vis('reader-card'));
await page.fill('#reader-name', 'Riya'); await page.click('#reader-save'); await sleep(500);
log('C saved: ready card', await vis('ready-card'), 'name', await page.textContent('#ready-name'), '| TV readers', JSON.stringify(tvMsgs.filter((m) => m.t === 'readers').at(-1)?.readers));
await page.click('#ready-btn'); await sleep(1200);
log('D session: state', await page.textContent('#state'), '| mic', await page.textContent('#mic'), '| wake', await page.textContent('#wake'));
const readerId = tvMsgs.filter((m) => m.t === 'readers').at(-1).readers[0].readerId;
const words = ['The', 'little', 'cat', 'ran', 'home.'];
const t0 = Date.now();
tv.send(JSON.stringify({ type: 'turn.start', turnId: 'T1', readerId, storyId: 'demo', page: 0, line: 3, words, lang: 'en-IN' }));
await sleep(1500);
log('E turn: phone state', await page.textContent('#state'), '| mic', await page.textContent('#mic'), '| words', await page.textContent('#words'));
for (let i = 0; i < 80 && !tvMsgs.some((m) => m.type === 'line.done'); i++) await sleep(100);
const ev = tvMsgs.filter((m) => ['mic.state', 'word.read', 'word.helped', 'word.skipped', 'line.done', 'turn.cancel'].includes(m.type));
log('F TV received:', ev.map((m) => `${m.type}${m.index !== undefined ? ':' + m.index : ''}${m.state ? ':' + m.state : ''}@${m.serverMs ? Math.round(m.serverMs - ev[0].serverMs) : ''}`).join('  '));
await sleep(600);
log('G after line.done: phone state', await page.textContent('#state'), '| mic', await page.textContent('#mic'), '| live tracks', await page.evaluate(() => [...window.wl.S.tracks].filter((t) => t.readyState === 'live').length));
tv.send(JSON.stringify({ t: 'session.end' })); await sleep(600);
log('H summary on phone:', await page.textContent('#summary'), '| on TV:', tvMsgs.find((m) => m.type === 'session.summary')?.text);
const tr = await (await fetch(`${BASE}/api/reading/traces?session=${sid}`)).json();
log('I trace:', JSON.stringify(tr.map((t) => ({ source: t.source, endReason: t.endReason, result: t.result, events: t.events.map((e) => e.kind[0] + e.index) }))));
const tel = await (await fetch(`${BASE}/api/sessions/${sid}/telemetry.json`)).json();
log('J audit live mic outside turns:', tel.filter((r) => r.kind === 'mic-violation').length, '| line-done rows', tel.filter((r) => r.kind === 'line-done').length);
await browser.close(); tv.close(); process.exit(0);
